List<String> testCardImage = [
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
  "assets/images/sample_image.png",
];

List<String> testInfoShareImage = [
  "assets/images/InfoShareSampleImage.jpg",
  "assets/images/InfoShareSampleImage.jpg",
  "assets/images/InfoShareSampleImage.jpg",
  "assets/images/InfoShareSampleImage.jpg",
  "assets/images/InfoShareSampleImage.jpg",
  "assets/images/InfoShareSampleImage.jpg",
  "assets/images/InfoShareSampleImage.jpg",
  "assets/images/InfoShareSampleImage.jpg",
  "assets/images/InfoShareSampleImage.jpg",
  "assets/images/InfoShareSampleImage.jpg",
  "assets/images/InfoShareSampleImage.jpg",
  "assets/images/InfoShareSampleImage.jpg"
];

List<String> testHomeTitleString = [
  "요로케 요양병원",
  "코로나 프리 요양병원",
  "요로나 요양병원",
  "코로케 요양병원",
];

List<String> testHomeDescString = [
  "지금 이용하실수 있는 혜택 3가지",
  "지금 이용하실수 있는 혜택 4가지",
  "지금 이용하실수 있는 혜택 5가지",
  "지금 이용하실수 있는 혜택 6가지",
];

List<String> testShortString = [
  "요양병원",
  "요양원",
  "복지관",
  "간병인",
  "요양병원",
  "요양원",
  "복지관",
  "간병인",
  "요양병원",
  "요양원",
  "복지관",
  "간병인",
  "요양병원",
  "요양원",
  "복지관",
  "간병인",
  "요양병원",
  "요양원",
  "복지관",
  "간병인",
  "요양병원",
  "요양원",
  "복지관",
  "간병인",
  "요양병원",
  "요양원",
  "복지관",
  "간병인",
  "요양병원",
  "요양원",
  "복지관",
  "간병인"
];

List<String> testLongString = [
  "1.요양병원질문",
  "2.요양원 선택 고민",
  "3.정홍규 인성 질문",
  "4.정홍규 똥오줌 고민",
  "5.요양병원질문",
  "6.요양원 선택 고민",
  "7.정홍규 인성 질문",
  "8.정홍규 똥오줌 고민",
  "9.요양병원질문",
  "10.요양원 선택 고민",
  "11.정홍규 인성 질문",
  "12.정홍규 똥오줌 고민",
  "13.요양병원질문",
  "14.요양원 선택 고민",
  "15.정홍규 인성 질문",
  "16.정홍규 똥오줌 고민",
  "1.요양병원질문",
  "2.요양원 선택 고민",
  "3.정홍규 인성 질문",
  "4.정홍규 똥오줌 고민",
  "5.요양병원질문",
  "6.요양원 선택 고민",
  "7.정홍규 인성 질문",
  "8.정홍규 똥오줌 고민",
  "9.요양병원질문",
  "10.요양원 선택 고민",
  "11.정홍규 인성 질문",
  "12.정홍규 똥오줌 고민",
  "13.요양병원질문",
  "14.요양원 선택 고민",
  "15.정홍규 인성 질문",
  "16.정홍규 똥오줌 고민",
];

List<String> testDate = [
  "2021.02.15",
  "2021.02.14",
  "2021.02.13",
  "2021.02.12",
  "2021.02.11",
  "2021.02.10",
  "2021.02.09",
  "2021.02.08",
  "2021.02.07",
  "2021.02.06",
  "2021.02.05",
  "2021.02.04",
  "2021.02.03",
  "2021.02.02",
  "2021.02.01",
  "2021.02.01",
  "2021.02.15",
  "2021.02.14",
  "2021.02.13",
  "2021.02.12",
  "2021.02.11",
  "2021.02.10",
  "2021.02.09",
  "2021.02.08",
  "2021.02.07",
  "2021.02.06",
  "2021.02.05",
  "2021.02.04",
  "2021.02.03",
  "2021.02.02",
  "2021.02.01",
  "2021.02.01",
];

List<String> testNumberString = [
  "1",
  "10",
  "12",
  "15k",
  "123",
  "11",
  "14",
  "15k",
  "11k",
  "10k",
  "12",
  "32k",
  "322k",
  "10k",
  "12",
  "32k",
  "1",
  "10",
  "12",
  "15k",
  "123",
  "11",
  "14",
  "15k",
  "11k",
  "10k",
  "12",
  "32k",
  "322k",
  "10k",
  "12",
  "32k",
];

List<int> testNumber = [
  1,
  2,
  3,
  4,
  3,
  5,
  0,
  3,
  2,
  5,
  2,
  3,
  1,
  4,
  4,
  1,
  2,
  3,
  4,
  3,
  5,
  0,
  3,
  2,
  5,
  2,
  3,
  1,
  4,
  4
];

List<String> infoShareHospitalTitle = [
  "병원1",
  "병원2",
  "병원3",
  "병원4",
  "병원5",
  "병원6",
  "병원7",
  "병원8",
];

class PostData {
  PostData(this.title, this.body, this.category, this.categoryIndex);

  late String title;
  late String body;
  late String category;
  late int categoryIndex;
}

PostData tempPostData = PostData("", "", "testPage", -1);

List<PostData> testPostData = <PostData>[];
